service: azure-ml-image-labeling-service

provider:
  name: azure
  location: North Europe
  runtime: nodejs10.x
  environment:
    COMPUTER_VISION_SUBSCRIPTION_KEY: ${env:COMPUTER_VISION_SUBSCRIPTION_KEY}
    COMPUTER_VISION_ENDPOINT: ${env:COMPUTER_VISION_ENDPOINT}

plugins:
  - serverless-dotenv-plugin
  - serverless-azure-functions

package:
  exclude:
    - local.settings.json
    - .vscode/**

functions:
  getImageLabels:
    handler: getImageLabels.handler
    events:
      - http: true
        x-azure-settings:
          name: req
          methods:
            - post
          authLevel: anonymous
      - http: true
        x-azure-settings:
          direction: out
          name: $return
